dependencies:
  build: 
    - python:3.6.3
    - anaconda3:4.3.30
    
build_targets:
  - name: init
    commands:
      - git submodule update --init --recursive
  - name: python36
    build_after:
      - init
    commands:
      - conda update --yes --quiet conda
      - conda python=3.6 pip Cython numpy scipy nose matplotlib pandas
      - bash continuous_integration/test_script.sh --exclude="^test_[a-p].*\.py"
      
ci:
  builds:
    - name: python3.6
      build_target: python36
